import React, { useState, useCallback } from 'react';
import api from '../../services/api';
import './AdminAIInsights.css';

// ─── Skeleton loader ────────────────────────────────────────────────────────
function Skeleton({ width = '100%', height = '16px', style = {} }) {
    return (
        <div
            className="ais-skeleton"
            style={{ width, height, ...style }}
            aria-hidden="true"
        />
    );
}

// ─── Health Score Ring ───────────────────────────────────────────────────────
function HealthRing({ score, label }) {
    const r = 52;
    const circ = 2 * Math.PI * r;
    const offset = circ - (score / 100) * circ;
    const color = score >= 80 ? '#22c55e' : score >= 60 ? '#f59e0b' : score >= 40 ? '#f97316' : '#ef4444';

    return (
        <div className="ais-ring-wrap" aria-label={`Health score: ${score} out of 100`}>
            <svg viewBox="0 0 120 120" className="ais-ring-svg">
                <circle cx="60" cy="60" r={r} className="ais-ring-bg" />
                <circle
                    cx="60" cy="60" r={r}
                    className="ais-ring-fg"
                    style={{
                        stroke: color,
                        strokeDasharray: circ,
                        strokeDashoffset: offset,
                    }}
                />
            </svg>
            <div className="ais-ring-inner">
                <span className="ais-ring-score" style={{ color }}>{score}</span>
                <span className="ais-ring-label">{label}</span>
            </div>
        </div>
    );
}

// ─── Stat Card ───────────────────────────────────────────────────────────────
function StatCard({ icon, label, value, sub, accent }) {
    return (
        <div className="ais-stat-card" style={{ '--accent': accent }}>
            <div className="ais-stat-icon">{icon}</div>
            <div className="ais-stat-info">
                <div className="ais-stat-value">{value}</div>
                <div className="ais-stat-label">{label}</div>
                {sub && <div className="ais-stat-sub">{sub}</div>}
            </div>
        </div>
    );
}

// ─── Main Page ───────────────────────────────────────────────────────────────
export default function AdminAIInsights() {
    const [state, setState] = useState('idle'); // idle | loading | done | error
    const [data, setData] = useState(null);
    const [error, setError] = useState('');
    const [lastRun, setLastRun] = useState(null);

    const runAnalysis = useCallback(async () => {
        setState('loading');
        setError('');
        try {
            const resp = await api.get('/ai/insights');
            if (resp.data.success) {
                setData(resp.data.data);
                setLastRun(new Date());
                setState('done');
            } else {
                throw new Error(resp.data.message || 'Analysis failed');
            }
        } catch (err) {
            setError(err.response?.data?.message || err.message || 'Failed to fetch insights.');
            setState('error');
        }
    }, []);

    const ins = data?.insights;
    const erp = data?.erpData;

    return (
        <div className="ais-page" id="ai-insights-page">
            {/* ── Page Header ── */}
            <div className="ais-hero">
                <div className="ais-hero-left">
                    <div className="ais-hero-badge">🤖 Powered by Groq LLaMA-3.3</div>
                    <h1 className="ais-hero-title">AI Insights Dashboard</h1>
                    <p className="ais-hero-desc">
                        Real-time agentic analysis of your ERP data — attendance trends, fee collection,
                        grade distribution, and actionable recommendations generated by AI.
                    </p>
                    {lastRun && (
                        <div className="ais-last-run">
                            Last analyzed: {lastRun.toLocaleString('en-IN')}
                        </div>
                    )}
                </div>
                <button
                    id="run-analysis-btn"
                    className={`ais-run-btn ${state === 'loading' ? 'ais-run-btn--loading' : ''}`}
                    onClick={runAnalysis}
                    disabled={state === 'loading'}
                >
                    {state === 'loading' ? (
                        <>
                            <span className="ais-spinner"></span>
                            Analyzing ERP Data…
                        </>
                    ) : (
                        <>
                            ⚡ {state === 'done' ? 'Re-Analyze' : 'Run AI Analysis'}
                        </>
                    )}
                </button>
            </div>

            {/* ── Idle State ── */}
            {state === 'idle' && (
                <div className="ais-idle">
                    <div className="ais-idle-icon">🔍</div>
                    <h3>Ready to Analyze</h3>
                    <p>Click "Run AI Analysis" to gather live ERP data and generate<br/>an AI-powered institutional health report.</p>
                    <div className="ais-idle-features">
                        <span>📊 Attendance Trends</span>
                        <span>💰 Fee Collection Rate</span>
                        <span>📝 Marks Distribution</span>
                        <span>📚 Library Status</span>
                        <span>⚠️ Anomaly Detection</span>
                        <span>💡 Recommendations</span>
                    </div>
                </div>
            )}

            {/* ── Error ── */}
            {state === 'error' && (
                <div className="ais-error">
                    <span>⚠️</span>
                    <strong>Analysis Failed</strong>
                    <p>{error}</p>
                    <button onClick={runAnalysis} className="ais-retry-btn">Retry</button>
                </div>
            )}

            {/* ── Loading Skeletons ── */}
            {state === 'loading' && (
                <div className="ais-results">
                    <div className="ais-top-row">
                        <div className="ais-summary-card ais-card">
                            <Skeleton height="20px" width="40%" style={{ marginBottom: 12 }} />
                            <Skeleton height="14px" style={{ marginBottom: 8 }} />
                            <Skeleton height="14px" width="85%" style={{ marginBottom: 8 }} />
                            <Skeleton height="14px" width="70%" />
                        </div>
                        <div className="ais-health-card ais-card">
                            <Skeleton width="120px" height="120px" style={{ borderRadius: '50%', margin: '0 auto 12px' }} />
                            <Skeleton height="16px" width="60%" style={{ margin: '0 auto' }} />
                        </div>
                    </div>
                    <div className="ais-stats-grid">
                        {[1,2,3,4].map(i => (
                            <div className="ais-stat-card ais-card" key={i}>
                                <Skeleton width="40px" height="40px" style={{ borderRadius: '10px', marginBottom: 12 }} />
                                <Skeleton height="20px" width="60%" style={{ marginBottom: 6 }} />
                                <Skeleton height="13px" width="80%" />
                            </div>
                        ))}
                    </div>
                    <div className="ais-bottom-row">
                        <div className="ais-anomalies-card ais-card">
                            <Skeleton height="18px" width="40%" style={{ marginBottom: 16 }} />
                            {[1,2,3].map(i => (
                                <Skeleton key={i} height="13px" style={{ marginBottom: 10 }} />
                            ))}
                        </div>
                        <div className="ais-recommendations-card ais-card">
                            <Skeleton height="18px" width="50%" style={{ marginBottom: 16 }} />
                            {[1,2,3].map(i => (
                                <Skeleton key={i} height="13px" style={{ marginBottom: 10 }} />
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* ── Results ── */}
            {state === 'done' && ins && erp && (
                <div className="ais-results" id="ai-insights-results">
                    {/* Top Row: Summary + Health Score */}
                    <div className="ais-top-row">
                        <div className="ais-summary-card ais-card" id="ai-summary-card">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">📋</span>
                                <h2 className="ais-card-title">AI Summary</h2>
                                <span className="ais-badge ais-badge--ai">AI Generated</span>
                            </div>
                            <p className="ais-summary-text">{ins.summary}</p>
                            <div className="ais-summary-meta">
                                <span>📅 {erp.summary_date}</span>
                                <span>👥 {erp.total_active_students?.toLocaleString('en-IN')} Active Students</span>
                            </div>
                        </div>

                        <div className="ais-health-card ais-card" id="ai-health-card">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">❤️</span>
                                <h2 className="ais-card-title">Health Score</h2>
                            </div>
                            {ins.health_score != null ? (
                                <HealthRing score={ins.health_score} label={ins.health_label} />
                            ) : (
                                <div className="ais-na">N/A</div>
                            )}
                        </div>
                    </div>

                    {/* Stats Grid */}
                    <div className="ais-stats-grid" id="ai-stats-grid">
                        <StatCard
                            icon="📊"
                            label="Overall Attendance (30 days)"
                            value={erp.attendance?.overall_rate_last_30_days}
                            sub={`${erp.attendance?.total_records?.toLocaleString('en-IN')} records`}
                            accent="#667eea"
                        />
                        <StatCard
                            icon="💰"
                            label="Fee Collection Rate"
                            value={erp.fees?.collection_rate}
                            sub={`₹${erp.fees?.due_amount} still pending`}
                            accent="#f59e0b"
                        />
                        <StatCard
                            icon="📝"
                            label="Top Grade"
                            value={erp.marks?.grade_distribution ? Object.entries(erp.marks.grade_distribution).sort((a,b) => b[1]-a[1])[0]?.[0] || 'N/A' : 'N/A'}
                            sub={`${erp.marks?.grade_distribution ? Object.entries(erp.marks.grade_distribution).sort((a,b) => b[1]-a[1])[0]?.[1] || 0 : 0} students`}
                            accent="#22c55e"
                        />
                        <StatCard
                            icon="📚"
                            label="Overdue Library Books"
                            value={erp.library?.overdue_books ?? 'N/A'}
                            sub={erp.library?.overdue_books > 0 ? 'Action needed' : 'All clear'}
                            accent={erp.library?.overdue_books > 0 ? '#ef4444' : '#22c55e'}
                        />
                    </div>

                    {/* Department Attendance Table */}
                    {erp.attendance?.by_department?.length > 0 && (
                        <div className="ais-card" id="ai-dept-table">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">🏛️</span>
                                <h2 className="ais-card-title">Department Attendance (Last 30 Days)</h2>
                            </div>
                            <div className="ais-table-wrap">
                                <table className="ais-table">
                                    <thead>
                                        <tr>
                                            <th>Department</th>
                                            <th>Attendance Rate</th>
                                            <th>Change vs Last Month</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {erp.attendance.by_department.map((d, i) => (
                                            <tr key={i}>
                                                <td>{d.department}</td>
                                                <td>
                                                    <div className="ais-progress-wrap">
                                                        <div className="ais-progress-bar"
                                                            style={{
                                                                width: d.attendance_rate,
                                                                background: parseFloat(d.attendance_rate) >= 75 ? '#22c55e' : '#ef4444'
                                                            }}
                                                        />
                                                        <span>{d.attendance_rate}</span>
                                                    </div>
                                                </td>
                                                <td className={parseFloat(d.change_vs_last_month) >= 0 ? 'ais-positive' : 'ais-negative'}>
                                                    {d.change_vs_last_month}
                                                </td>
                                                <td>
                                                    <span className={`ais-badge ais-badge--${d.flag?.toLowerCase()}`}>
                                                        {d.flag === 'OK' ? '✅ OK' : d.flag === 'WATCH' ? '⚠️ Watch' : '🔴 Low'}
                                                    </span>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )}

                    {/* Bottom Row: Anomalies + Recommendations */}
                    <div className="ais-bottom-row">
                        <div className="ais-anomalies-card ais-card" id="ai-anomalies-card">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">⚠️</span>
                                <h2 className="ais-card-title">Anomalies Detected</h2>
                                <span className="ais-count-badge">{ins.anomalies?.length || 0}</span>
                            </div>
                            {ins.anomalies?.length > 0 ? (
                                <ul className="ais-list ais-list--anomaly">
                                    {ins.anomalies.map((item, i) => (
                                        <li key={i} className="ais-list-item">
                                            <span className="ais-list-dot">⚠</span>
                                            {item}
                                        </li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="ais-empty">No anomalies detected. System is performing well!</p>
                            )}
                        </div>

                        <div className="ais-recommendations-card ais-card" id="ai-recommendations-card">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">💡</span>
                                <h2 className="ais-card-title">AI Recommendations</h2>
                                <span className="ais-count-badge">{ins.recommendations?.length || 0}</span>
                            </div>
                            {ins.recommendations?.length > 0 ? (
                                <ol className="ais-list ais-list--rec">
                                    {ins.recommendations.map((item, i) => (
                                        <li key={i} className="ais-list-item">
                                            <span className="ais-list-num">{i + 1}</span>
                                            {item}
                                        </li>
                                    ))}
                                </ol>
                            ) : (
                                <p className="ais-empty">No specific recommendations at this time.</p>
                            )}
                        </div>
                    </div>

                    {/* Grade Distribution */}
                    {erp.marks?.grade_distribution && Object.keys(erp.marks.grade_distribution).length > 0 && (
                        <div className="ais-card" id="ai-grade-dist">
                            <div className="ais-card-header">
                                <span className="ais-card-icon">📝</span>
                                <h2 className="ais-card-title">Grade Distribution</h2>
                            </div>
                            <div className="ais-grade-grid">
                                {Object.entries(erp.marks.grade_distribution)
                                    .sort((a, b) => b[1] - a[1])
                                    .map(([grade, count]) => {
                                        const gradeColors = {
                                            O: '#22c55e', 'A+': '#10b981', A: '#14b8a6',
                                            'B+': '#3b82f6', B: '#6366f1', C: '#8b5cf6',
                                            D: '#f59e0b', F: '#ef4444', Ungraded: '#6b7280'
                                        };
                                        return (
                                            <div key={grade} className="ais-grade-item">
                                                <div className="ais-grade-badge" style={{ background: gradeColors[grade] || '#6b7280' }}>
                                                    {grade}
                                                </div>
                                                <div className="ais-grade-count">{count?.toLocaleString('en-IN')}</div>
                                                <div className="ais-grade-label">students</div>
                                            </div>
                                        );
                                    })
                                }
                            </div>
                        </div>
                    )}

                    <div className="ais-footer-note">
                        Analysis generated at {data?.generated_at ? new Date(data.generated_at).toLocaleString('en-IN') : '—'}
                        &nbsp;· Source: {data?.source === 'groq-agent' ? '🤖 Groq LLaMA-3.3 + Live ERP Data' : '📊 ERP Data Only (AI unavailable)'}
                    </div>
                </div>
            )}
        </div>
    );
}
